version: '3'

services:
  database:
    restart: always
    image: 'postgres:14.2-alpine'
    container_name: database
    networks:
      - app-network
    ports:
      - '5432:5432'
    volumes:
      - db-storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}

  server:
    container_name: server
    networks:
      - app-network
    build:
      context: .
      dockerfile: Dockerfile
    command: ./wait-for-postgres.sh database ./main -p
    depends_on:
      - database
    env_file:
      - prod.env
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - 8081:8081

volumes:
  minio-storage:
  db-storage:

networks:
  app-network:
